### ISSUE TITLE
[feature request] create 404.html by default

### ISSUE THREAD

**Issue by gkucmierz** [angular-buch/angular-cli-ghpages#10]
<img width="597" alt="zrzut ekranu 2017-02-19 o 14 43 33" src="https://cloud.githubusercontent.com/assets/739084/23102892/d377863e-f6b1-11e6-8b76-724ff340d09d.png">

**Comment by JohannesHoppe** [comment]
ok, it's on my list

**Comment by JohannesHoppe** [comment]
I decided to make this a default. It will now always copy `index.html` to `404.html` without any option to adjust. If there is no index.html, than a message is printed.

**Comment by JohannesHoppe** [comment]
Please test `angular-cli-ghpages@0.5.1`!
