### ISSUE TITLE
DeprecationWarning: Unhandled promise rejections are deprecated. 

### ISSUE THREAD

**Issue by JohannesHoppe** [angular-buch/angular-cli-ghpages#11]
by @tkow 
from https://github.com/angular/angular-cli/pull/4385#issuecomment-280826566

However, I have another problem catch message says "An error occurred!" in node v.7.4.0.
and details bellow.

```
(node:6042) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: Unspecified error (run without silent option for detail)
(node:6042) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Please tell me how it cause to address, if there are someone feel not uncomfortable.I'll try to downgrade node version.Then , I move to angular-buch/angular-cli-ghpages repository for this ploblem is not angular-cli.

**Comment by JohannesHoppe** [comment]
@tkow This warning should be pretty easy to fix.

**Comment by tkow** [comment]
@JohannesHoppe Thanks for fix.I'll check it.

**Comment by JohannesHoppe** [comment]
Just catching the promise and then displaying it with console.log. Right now I let it go through so that node.js complains.

**Comment by hiepxanh** [comment]
how to resolve this issue ?

**Comment by JohannesHoppe** [comment]
There are two aspects:

1. A dprecation. Don't worry, right now it's just a warning. I should fix that one day.
2. But there is also a hidden error. Please refer to https://github.com/angular-buch/angular-cli-ghpages#--no-silent if you want to see the content.

**Comment by hiepxanh** [comment]
wow, so quickly, I love this. Thanks you so much, I don't feel worry any more

**Comment by hiepxanh** [comment]
![image](https://cloud.githubusercontent.com/assets/16970990/23656087/d0d8b586-036a-11e7-970e-29fa60aae012.png)
why ? it push successful after i run no silent ! Oh my god !!!!!!!!!!!!

**Comment by JohannesHoppe** [comment]
Fixed by https://github.com/angular-buch/angular-cli-ghpages/commit/3f40bd1343ca122a5acabba6be1b89df8f6e2423

**Comment by gapgag55** [comment]
I solved by using "sudo angular-cli-ghpages"
