### ISSUE TITLE
404s when loading on github

### ISSUE THREAD

**Issue by tschiman** [angular-buch/angular-cli-ghpages#13]
![image](https://cloud.githubusercontent.com/assets/3507131/23982915/5765ec42-09d6-11e7-9735-4b7191794c92.png)

I have 404s on nearly all my build files and I can't figure out what setting I need to get these to resolve. My project source is here: [](https://github.com/tschiman/pick-a-color)

The offending page is here: [](https://tschiman.github.io/pick-a-color/)

I'm obviously new to angular 2 and building to github. But from your wiki this seems like I'm doing something dumb. If anyone could be so kind as to point it I would really appreciate it.

**Comment by JohannesHoppe** [comment]
During `ng build`, you have to set up the `--base-href` correctly!

Please also copy index.html to 404.html before publishing. ( https://github.com/angular-buch/angular-cli-ghpages/wiki/FAQ#why-is-the-routing-not-working-correctly-on-hard-reload-specific-to-github-pages-only ) --> this will be fixed soon.

**Comment by JohannesHoppe** [comment]
Oh, I see that this is a user page!
What was the executed command?

**Comment by tschiman** [comment]
Thanks Johannes this solved it.
