### ISSUE TITLE
could not read Username for 'https://github.com': Invalid argument

### ISSUE THREAD

**Issue by aGoncharuks** [angular-buch/angular-cli-ghpages#14]
Hi

I'm following usage guide, but see error from issue name. What can be the reason? Here is my log with no-silent option:
...
Copying files
Adding all
Committing
Pushing
An error occurred!
(node:5644) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): ProcessError: bash: /dev/tty: No such device or address
error: failed to execute prompt script (exit code 1)
fatal: could not read Username for 'https://github.com': Invalid argument

**Comment by JohannesHoppe** [comment]
Are you on windows?
This is a git issue, please try out the various solutions:
https://github.com/atom/atom/issues/8984

... and post the working solution!

**Comment by karlmartin94** [comment]
For me the solution to this was updating the remote URL to:

git remote set-url https://<username>:<password>@github.com/<username>/<repo_name>.git

**Comment by rashid-softordi** [comment]
@aGoncharuks 

@tsupol 
**# Issue is SOLVED!**
_error: failed to execute prompt script (exit code 1) fatal: 
could not read Username for 'https://github.com': Invalid argument_    

1- Create a ssh key using Git Bash using following command

`ssh-keygen -t rsa -b 4096 -C "your-github@email.com" `

After running this command just install the by default options and enter the password balnk when it prompts. 

2- Then run the following commands to locate the public/private key generated from step1

`cd .ssh`

`cd ~/.ssh`

3- Then run the following command to view your public: 

`cat id_rsa.pub`

4- Copy your public key and go to  your GitHub account -> settings -> create a SSH and GPG keys then click new ssh key and past your public key in the in key text field.

5- Verify your public key using Git Bash by running the following command:

`ssh -vT git@github.com `

You will get output like this

> debug1: channel 0: free: client-session, nchannels 1
> Transferred: sent 3848, received 2040 bytes, in 0.2 seconds
> Bytes per second: sent 16032.4, received 8499.5
> debug1: Exit status 1
 
Then you no longer got "could not read Username for 'https://github.com': Invalid argument"

**Comment by JohannesHoppe** [comment]
Thanks for summarizing the golden way with proper certificates.
Please also keep in mind that GH_TOKENs are much more easy to setup. See the README for that.

**Comment by rashid-softordi** [comment]
@JohannesHoppe 

I answer with best possible solution according  to  problem.

**Comment by JohannesHoppe** [comment]
@rashid-softordi Many thanks for that great tutorial!

**Comment by ragv1** [comment]
Also had this issue an solved it creating a GH_TOKEN like described in [here](https://help.github.com/articles/creating-a-personal-access-token-for-the-command-line/) , then running the ngh command with the repo flag like this: `ngh --repo=https://(your GH_TOKEN)@github.com/your-username/your-repo.git`. And that was all for me.

**Comment by JohannesHoppe** [comment]
@ragv1 Did you set up the environment variable GH_TOKEN, too?
See:

https://github.com/angular-schule/angular-cli-ghpages/issues/20#issuecomment-304200945

**Comment by ragv1** [comment]
@JohannesHope No i did not. I just save the GH_TOKEN in a text file and copy/ paste whenever i needed.

**Comment by taitruong** [comment]
Hi, I want to create a blog based on Angular 6 and hosted by GitHub pages. I was thinking of displaying on the left side a list of all blogs. Now I wonder how can I read all markdown files e.g. from a blogs/ subfolder and display it in my component. Is it somehow possible to read from a local folder and generate a static page?

**Comment by munna** [comment]
> For me the solution to this was updating the remote URL to:
> 
> `git remote set-url https://<username>:<password>@github.com/<username>/<repo_name>.git`

This will only work if password does not contain "@" symbol.

**Comment by adititipnis** [comment]
This helped

Try adding this into your git config

> [credential]
>     helper = wincred
> or via console
> 
> git config --global credential.helper wincred

**Comment by khatridev** [comment]
delete ..node_modules/gh-pages/.cache folder
run- `git config --global credential.helper wincred`

poup may come again and throw error. 

If pops up, delete the git credentials manually from Windows Credential Manager.
For windows to remember the password, use some other commands ( I created a branch and deleted, it asked me username/password on the terminal)

after this I ran my command, pop up never came.

**Comment by Gesugao-san** [comment]
> > For me the solution to this was updating the remote URL to:
> > `git remote set-url https://<username>:<password>@github.com/<username>/<repo_name>.git`
> 
> This will only work if password does not contain "@" symbol.

And if password does not contain "|" symbol.

**Comment by steven1lung** [comment]
> > > For me the solution to this was updating the remote URL to:
> > > `git remote set-url https://<username>:<password>@github.com/<username>/<repo_name>.git`
> > 
> > 
> > This will only work if password does not contain "@" symbol.
> 
> And if password does not contain "|" symbol.

Just to share how I did it. I used an access token to get access.
I added it to the repo's secrets, then access them via ${{secrets.XXXXX}} . 
It would be like:
```
git remote set-url origin https://${{secrets.ACCESS_TOKEN}}@github.com/<username>/<repo_name>
```
