### ISSUE TITLE
Can only enter page from root

### ISSUE THREAD

**Issue by tschaka1904** [angular-buch/angular-cli-ghpages#15]
I used the angular-cli-ghpages tool and it worked perfectly fine, with deploying it on the gh-pages branch. But I only can access my application from the root directory and not just using a specific URL. 

Has anyone came across this problem?

**Comment by JohannesHoppe** [comment]
see https://github.com/angular-buch/angular-cli-ghpages/wiki/FAQ#why-is-the-routing-not-working-correctly-on-hard-reload-specific-to-github-pages-only

**Comment by tschaka1904** [comment]
Thanks @JohannesHoppe!

**Comment by JohannesHoppe** [comment]
I will add this be default to the next version -- when I have some spare time.

**Comment by tschaka1904** [comment]
Great stuff!
