### ISSUE TITLE
Image Asset Resolution Misses Repo Name

### ISSUE THREAD

**Issue by tomwanzek** [angular-buch/angular-cli-ghpages#16]
Following the instructions to publish to gh-pages for a specified repo `REPOSITORY`:
```
ng build --prod --base-href "https://USERNAME.github.io/REPOSITORY/"
ngh [OPTIONS]
```
leads to an issue with properly resolving image assets in components.

I.e. assume a `png` image  is stored in the angular/cli `assets` folder. It is used in a component template:
```html
<img src="/assets/some-image.png" class="img-responsive" />
```

While the assets folder is properly created in the `gh-pages` branch including the image, the image resolution in the Angular app on `github.io` fails. The resolution is attempted at:
```
https://USERNAME.github.io/assets/some-image.png
```
instead of

```
https://USERNAME.github.io/REPOSITORY/assets/some-image.png
```

Is there a way to address this issue as part of the publish process? As a hack, the image `src` can be prefixed through a manual commit to the `gh-pages` branch to wedge in the repo name. On a small repo like [d3-ng2-demo](https://github.com/tomwanzek/d3-ng2-demo) this is  viable, but certainly not in general.

Thanks in advance for suggestions addressing this issue.

**Comment by JohannesHoppe** [comment]
`--base-href` will only rewrite the `<base href` of the `index.html`. It's not supposed to change images.
You are supposed to use relative pathes.

**Comment by tomwanzek** [comment]
My bad, I changed the `src` to drop the leading `/` and all is fine. If I recall correctly, I added the leading `/` in when one of the cli-betas exhibited some odd behaviour just after `assets` replaced `public` and `ng deploy` was still implemented. Back then it worked fine.

I just migrated the repo over to cli 1.0.0 and used this utility to push the github pages.

Thx! T

**Comment by JohannesHoppe** [comment]
:smile:
