### ISSUE TITLE
Doest not deploy to gh-pages

### ISSUE THREAD

**Issue by adityarb88** [angular-buch/angular-cli-ghpages#17]
Hi

I am following the same steps that you have mentioned in the usage section but I am unable to publish to gh-pages. The build completes successfully and the `ngh` command also runs without any issues. Here is a screenshot:

![image](https://cloud.githubusercontent.com/assets/1426805/25389048/6d326b54-2984-11e7-818b-188eaed056e5.png)

When I see my github repo, I see only one branch:
![image](https://cloud.githubusercontent.com/assets/1426805/25389141/a7e3372e-2984-11e7-8d53-468515379490.png)

Could you please let me know what I am missing?

**Comment by JohannesHoppe** [comment]
`ngh` is a separate command, you are missing one newline between!

**Comment by adityarb88** [comment]
Thanks!
