### ISSUE TITLE
/dist in .gitignore

### ISSUE THREAD

**Issue by zakaria-soufiani** [angular-buch/angular-cli-ghpages#18]
After running the commands to deploy the app to Github pages, the app is deployed to Github but the URL  `https://USER-NAME.github.io/REPO-NAME` shows just the Loading... heading. The workaround that I found was to remove the `/dist` folder from the` .gitignore` before deploying. It used to work fine and only encountered this problem today.

**Comment by JohannesHoppe** [comment]
Your setup must be wrong, e.g you reference files from `/dist` or something else. Please press `F12` and look for errors in chrome!

Here are some repos that all have `/dist` in the `.gitignore` and all of them are deployable with `angular-cli-ghpages`:

- https://github.com/angular-buch/book-monkey2
- https://github.com/angular-buch/angular-quotes
- https://github.com/angular-buch/book-monkey-rdx
