### ISSUE TITLE
Routing and 404 file not found

### ISSUE THREAD

**Issue by amivit** [angular-buch/angular-cli-ghpages#19]
Any solution to this? My starting url works to navigate around, but sharing a url with a friend, gives the github 404 file not found error message. You can test it here http://tech-flex.com/RSMuseum-ng/ Navigate to a different page and press f5

**Comment by MurhafSousli** [comment]
@amivit Github pages does not act as a normal server do, it just host your files on the base address.

To fix this simply use the hash location strategy
so instead of ` http://tech-flex.com/RSMuseum-ng/`  which is unknown to github
It will be `http://tech-flex.com/#/RSMuseum-ng/`

**Comment by JohannesHoppe** [comment]
Nope, you don't need to change the strategy.
See this wiki entry:
https://github.com/angular-buch/angular-cli-ghpages/wiki/FAQ#why-is-the-routing-not-working-correctly-on-hard-reload-specific-to-github-pages-only

But anyway, I will start to implement a solution now. Nobody reads the wiki! ;-)

**Comment by JohannesHoppe** [comment]
Please test `angular-cli-ghpages@0.5.1`!

**Comment by amivit** [comment]
Most importantly, `angular-cli-ghpages@0.5.1` works perfectly, thank you! I also tried copying the index.html to 404.html, as described in the previous wiki article. That worked too, but the automation from 0.5.1 is lovely.
