### ISSUE TITLE
Error , i didnt find in readme what i need

### ISSUE THREAD

**Issue by miroslavsopta** [angular-buch/angular-cli-ghpages#21]
Still didnt find in readme what i need about that set remote url ,

**Comment by miroslavsopta** [comment]
Replace the origin repo url
using git remote set-url "" because when you type "ngh --no-silent" command by default it will publish to git origin

Somone can mybe give example?

**Comment by JohannesHoppe** [comment]
https://github.com/angular-buch/angular-cli-ghpages#extra
