### ISSUE TITLE
404 error

### ISSUE THREAD

**Issue by roopkt** [angular-buch/angular-cli-ghpages#22]
It deployed successfully however not able to load page because of 404 error for downloading .css or. Js files.  Please checkout my link and see the network error. 
https://roopkt.github.io/ngrx-store-sample-app/

**Comment by JohannesHoppe** [comment]
That's not very much related to `angular-cli-ghpages` at all.
You have to adjust the `<base href="/">` and other things during build. Have a look at the examples in the [README.MD](https://github.com/angular-buch/angular-cli-ghpages#usage).

For example:
```
ng build --prod --base-href "/ngrx-store-sample-app/"
ngh
```
