### ISSUE TITLE
fatal: could not read Username for 'https://github.com': No error

### ISSUE THREAD

**Issue by hamzahamidi** [angular-buch/angular-cli-ghpages#26]
angular-cli-ghpages --no-silent
Cloning https://github.com/hamzahamidi/angular-sample.git into ..\AppData\Roaming\npm\node_modules\angular-cli-ghpages\node_modules\gh-pages\.cache

Cleaning

Fetching origin

Checking out origin/gh-pages

Removing files

Copying files

Adding all

Committing

Pushing

An error occurred!
 { ProcessError: bash: /dev/tty: No such device or address
error: failed to execute prompt script (exit code 1)
fatal: could not read Username for 'https://github.com': No error

    at ChildProcess.<anonymous> (C:\Users\Hamza\AppData\Roaming\npm\node_modules\angular-cli-ghpages\node_modules\gh-pages\lib\git.js:47:23)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:891:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
  code: 128,
  message: 'bash: /dev/tty: No such device or address\nerror: failed to execute prompt script (exit code 1)\nfatal: could not read Username for \'https://github.com\': No error\n',
  name: 'ProcessError' }

**Comment by JohannesHoppe** [comment]
You need more command line options, see this: https://github.com/angular-buch/angular-cli-ghpages#extra
