### ISSUE TITLE
Deployed site: Uncaught SyntaxError: Unexpected token <

### ISSUE THREAD

**Issue by TyrantWave** [angular-buch/angular-cli-ghpages#27]
After building the site with:

`ng build --prod --base-href "https;//<username>.github.io/<reponame>/`

I can run the site with no issues on a local server.

However, after publishing via `ngh`, the online site just gives the following error 4 times:

` SyntaxError: Unexpected token <             (index):1`

No other errors or information is given, so I have no idea what to do.

**Comment by TyrantWave** [comment]
Ok, so the issue was by default angular doesn't have the `_config.yml` file, which took a lot of digging around to find out was needed.

**Comment by JohannesHoppe** [comment]
Which config file? Could you explain your solution in detail?! :smile:

**Comment by TyrantWave** [comment]
From my understanding, github pages require a `_config.yml` file, so the project structure I uploaded had to look like the following:

```
| assets/
+   | files
| _config.yml
| index.html
| inline/main/polyfills/styles/vendor.js
```

Until I had `_config.yml`, the site would constantly fail with the error in the original post. It worked as soon as the file was present.

Inside `_config.yml` I specified the base URL:
`baseurl: /ng2-parallaxscroll`

Here's the full project, check the `origin/docs` branch for the website source, and the `gh-pages` for the built output: https://github.com/TyrantWave/ng2-parallaxscroll

To add the `_config.yml` to the output, I added it to the `angular.cli.json` assets folder:
```
  "apps": [
    {
      "root": "src",
      "outDir": "dist",
      "assets": [
        "assets",
        "favicon.ico",
        "_config.yml"
      ],
  ...
  ]
```

**Comment by JohannesHoppe** [comment]
This is strange. I have a lot of gh-pages repos, that have all no `_config.yml` at all.
See this, for example:

* https://github.com/angular-schule/2017-08-angular-workshop-wiesbaden/tree/master/book-rating --> directory `book-rating` from #master goes to #gh-pages
* Result: https://angular-schule.github.io/2017-08-angular-workshop-wiesbaden/

**Comment by bot101** [comment]
I am having this same issue with an app hosted on heroku. Works perfectly on my local system but remote builds on heroku throws the same error. A look at the generated .js files (vendor.hash.js, main.hash.js, inline.hash.js, scripts.hash.js & polyfills.hash.js) in the console shows HTML elements in the generated files.

**Comment by JohannesHoppe** [comment]
I bet this is related to you heroku deployment. Did you added the static pages buildpack?
 (https://github.com/heroku/heroku-buildpack-static). You could also go for a full SSR solution (express, see https://angular.io/guide/universal) This is what we do for https://angular-buch.com and https://angular.schule . Heroku automatically adds the buildpack for node.js.

**Comment by bot101** [comment]
@JohannesHoppe I have resolved the issue. I moved `app.listen(process.env.PORT || 8080);` before all definitions of `app.use` and routes.

**Comment by ParasRocks** [comment]
i have the same issue but not getting any solution?

**Comment by JohannesHoppe** [comment]
All our websites run on heruko, not on GitHub pages. We still use angular-cli-pages to push to a second for repo. I can't help here without more information. See my last response from 2 month ago. I'm pretty much sure that your heroku app or whatever you are running is not correctly configured.

**Comment by fmalcher** [comment]
@gstolfo This is about Angular 2+, so there is no `angular.json`/`.angular-cli.json` for you.
The `_config.yml` is specific for GitHub Pages/Jekyll.

**Comment by gstolfo** [comment]
Tks @fmalcher

**Comment by vaibhav269** [comment]
I was facing the same issue .This is due the creation of project directory inside the dist folder which is not being pointed by index.html.
Fixed it by changing the base tag from  <base href="/"> to  <base href="/project-app/"> inside index.html file.

**Comment by nvkhanh08t4** [comment]
Thank @vaibhav269 . Great!

**Comment by horlabyc** [comment]
> I was facing the same issue .This is due the creation of project directory inside the dist folder which is not being pointed by index.html.
> Fixed it by changing the base tag from `<base href="/"> `to `<base href="/project-app/">` inside index.html file.

This worked for me. Thanks

**Comment by yelinedinaresh** [comment]
I couldn't replicate the syntax error. Creating scripts directly in the console is fine for some things, but in this case a standalone HTML file with script might be more helpful for you to debug this issue.

**Comment by kapilSoni101** [comment]
@vaibhav269 :here /project-app/ mean-- project live URL  or anything else?

**Comment by chetna-raghav** [comment]
> I was facing the same issue .This is due the creation of project directory inside the dist folder which is not being pointed by index.html.
> Fixed it by changing the base tag from `<base href="/"> `to `<base href="/project-app/">` inside index.html file.

thanks this works for me
