### ISSUE TITLE
Deploy to a User GitHub Page

### ISSUE THREAD

**Issue by Programazing** [angular-buch/angular-cli-ghpages#28]
After reading up on GutHub Pages I found out that if you want to use a User/Org repository on GitHub Pages instead of a project repository (<UserName>.github.io vs. <UserName>.github.io/Project-Name ) you have to store everything in the master branch.

I was wondering if angular-cli-ghpages had a way to deal with this or if it's better to just create a repository for a website?

I'm asking because I'd like to use programazing.github.io as a portfolio/resume website even though I will eventually use a custom domain later on.

**Comment by Programazing** [comment]
I figured it out. I was trying to publish from the source files in the master branch to the master branch which would just overwrite everything.

You have to create a branch for the source files, switch to that branch, build it using prod, then publish using `ngh --branch=master`.

**Comment by JohannesHoppe** [comment]
Exactly! :smile: I prefer two Repos for that, to keep things clean .

**Comment by Programazing** [comment]
@JohannesHoppe Just a suggestion but could you add a mention to that somewhere in the project in case others don't know about the special rule for username and org pages?

**Comment by JohannesHoppe** [comment]
I'm sorry, my time is super rare right now!
But I made you a collaborator. Feel free to add a note to the wiki or the README.md :smile: :+1:
