### ISSUE TITLE
Better command line options / Unhandled promise rejection

### ISSUE THREAD

**Issue by scottschafer** [angular-buch/angular-cli-ghpages#6]
First, I wasn't clear if I was supposed to replace USERNAME and REPOSITORY here:
ng build --prod --base-href "https://USERNAME.github.io/REPOSITORY"

I *assumed* I was supposed to do that, so I first did this:

 ng build --prod --base-href "https://github.com/scottschafer/toilet-run"

I get this error when I run "ngh":

> An error occurred!
> 
> (node:36422) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: Unspecified error (run without silent option for detail)
> 

I tried "ngh --silent=false" and other variations, but it give me no more details.

**Comment by JohannesHoppe** [comment]
The Angular-CLI command `ng build` has nothing to do with the `ngh` command. The fist line in the example is just demonstrating that you have to build your app first, and that you most probably want to set up the `<base href="/">` via `--base-href`.

However, `UnhandledPromiseRejectionWarning` means that git can't connect to your repository.
Please try out:

```
angular-cli-ghpages --repo=https://GH_TOKEN@github.com/organisation/your-repo.git
```
Read more about [Github tokens here.](https://help.github.com/articles/creating-an-access-token-for-command-line-use/).

I will keep that issue open, since the command definitely needs better error messages! :smile:

**Comment by JohannesHoppe** [comment]
I also realised that the API is confusing. Please stay tuned for `--no-silent` and `--no-dotfiles`-

**Comment by JohannesHoppe** [comment]
Ok, this should be fixed now!
Please run `npm i -g angular-cli-ghpages@0.5.0` and try out `ngh --no-silent` for detailed information.

**Comment by mazyvan** [comment]
Doesn't work!!!

**Comment by JohannesHoppe** [comment]
This was not very helpful... 😞

**Comment by sampathar** [comment]
I get this error when I run "ngh":
An error occurred!
 Error: Unspecified error (run without silent option for detail)
    at C:\Users\Sampath Kumar\AppData\Roaming\npm\node_modules\angular-cli-ghpages\node_modules\gh-pages\lib\index.js:23
2:19
    at _rejected (C:\Users\Sampath Kumar\AppData\Roaming\npm\node_modules\angular-cli-ghpages\node_modules\q\q.js:844:24
)
    at C:\Users\Sampath Kumar\AppData\Roaming\npm\node_modules\angular-cli-ghpages\node_modules\q\q.js:870:30
    at Promise.when (C:\Users\Sampath Kumar\AppData\Roaming\npm\node_modules\angular-cli-ghpages\node_modules\q\q.js:112
2:31)
    at Promise.promise.promiseDispatch (C:\Users\Sampath Kumar\AppData\Roaming\npm\node_modules\angular-cli-ghpages\node
_modules\q\q.js:788:41)
    at \AppData\Roaming\npm\node_modules\angular-cli-ghpages\node_modules\q\q.js:604:44
    at runSingle (\AppData\Roaming\npm\node_modules\angular-cli-ghpages\node_modules\q\q.js:137:13
)
    at flush (r\AppData\Roaming\npm\node_modules\angular-cli-ghpages\node_modules\q\q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by JohannesHoppe** [comment]
Please read the full README and try out `ngh --no-silent` for detailed information. Ngh is silent by default for security reasons.

**Comment by sampathar** [comment]
Now it worked.
My repo has two remote origins, by default it is selecting the remote named origin.
When I replaced the remote origin it worked.
Thanks 👍

**Comment by JohannesHoppe** [comment]
Good point. Right now you can only setup the branch, not the remote. But the preferred way is still the `--repo` against a full URL.

**Comment by miroslavsopta** [comment]
I also have this error as sampathar, can y be more precise what need to be done?

**Comment by sampathar** [comment]
Replace the origin repo url
using git remote set-url "<repo url to publis github pages>" because when you type **"ngh --no-silent"** command by default it will publish to git origin

**Comment by miroslavsopta** [comment]
i am not that good , can y explain bit further, which remote url i need to replace,some example?

**Comment by JohannesHoppe** [comment]
Please read the README first. On the very bottom is an example.

**Comment by JohannesHoppe** [comment]
I locked the conversation, since the original problem was solved. Please open a new issue, in case of troubles.
