### ISSUE TITLE
Deployed url!

### ISSUE THREAD

**Issue by AbdallahBedir** [angular-buch/angular-cli-ghpages#8]
I finished the steps and Successfully published! in the end , but I cannot find the deployed url ?!

**Comment by JohannesHoppe** [comment]
Good point!
I added a new FAQ entry:
https://github.com/angular-buch/angular-cli-ghpages/wiki/FAQ

-----

Go to you repository settings, scroll down to the `GitHub Pages` section:

![Screenshot](https://raw.githubusercontent.com/wiki/angular-buch/angular-cli-ghpages/images/ghpages_url.png)
